[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

test = "test"
cache_path = "cache"

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false

ffi = false
fs_permissions = [{ access = "read", path = "./" }]

verbosity = 2

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 15
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
