

[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@aave/core-v3/=lib/aave-v3-core/",
]

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}] 

[fuzz]
runs = 256          
max_test_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
